// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    return null;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3GDsVga3WbCoFc9xs24INhMbTJwKPvOE',
    appId: '1:195855149817:web:3a1b1776b6d65c04131028',
    messagingSenderId: '195855149817',
    projectId: 'flutter-puzzle-hack-35f89',
    authDomain: 'flutter-puzzle-hack-35f89.firebaseapp.com',
    storageBucket: 'flutter-puzzle-hack-35f89.appspot.com',
    measurementId: 'G-J2LWDW7KYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbWmYvaqyEosN3YyCkWYT8QOEmkBlX4YM',
    appId: '1:195855149817:android:e372ce77aecf0caa131028',
    messagingSenderId: '195855149817',
    projectId: 'flutter-puzzle-hack-35f89',
    storageBucket: 'flutter-puzzle-hack-35f89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoE-TU7Uz3eCTP7otKwWvSqYgp3-c-034',
    appId: '1:195855149817:ios:8d7713acef615702131028',
    messagingSenderId: '195855149817',
    projectId: 'flutter-puzzle-hack-35f89',
    storageBucket: 'flutter-puzzle-hack-35f89.appspot.com',
    iosClientId: '195855149817-6g6eokoj7a5iq1j3qtjvv8cqjla7bpl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChallenge2022Clean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoE-TU7Uz3eCTP7otKwWvSqYgp3-c-034',
    appId: '1:195855149817:ios:8d7713acef615702131028',
    messagingSenderId: '195855149817',
    projectId: 'flutter-puzzle-hack-35f89',
    storageBucket: 'flutter-puzzle-hack-35f89.appspot.com',
    iosClientId: '195855149817-6g6eokoj7a5iq1j3qtjvv8cqjla7bpl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChallenge2022Clean',
  );
}
