include: package:flutter_lints/flutter.yaml

linter:
 rules:
    avoid_print: false

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    import_of_legacy_library_into_null_safe: ignore
    todo: ignore
  exclude:
    - "lib/**/*.pb*.dart"