name: Build
on: [push]
jobs:
  Update-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: appwrite/setup-for-actions@v1
        with:
          endpoint: '${{ secrets.APPWRITE_ENDPOINT }}'
          project: '${{ secrets.APPWRITE_PROJECT }}'
          key: '${{ secrets.APPWRITE_API_KEY }}'
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.14.0
      - name: Deploy all cloud functions
        run: ./server/scripts/deploy.sh